Update maven.yaml

diff --git a/.github/workflows/maven.yaml b/.github/workflows/maven.yaml
--- a/.github/workflows/maven.yaml
+++ b/.github/workflows/maven.yaml
@@ -21,3 +21,8 @@ jobs:
         cache: maven
     - name: Build with Maven
       run: mvn package --file pom.xml
+
+    - name: Post job cleanup
+      run: |
+        export ACTIONS_RUNNER_DEBUG=true
+        /usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/charles/project-folder/Task-Master-Pro/actions-runner/_work/Task-Master-Pro/Task-Master-Pro --files-from manifest.txt --use-compress-program zstdmt || echo "Cache save failed"
